apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-iiiq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vigneshsri-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-iiiq@sha256:e99cfd039bf60be359b4812e7c1185c32be30bae2653f4cb0320afc4e41728bc
        name: my-go
        resources: {}
status: {}
